#!/usr/bin/env bash
# Configure a load balancer
sudo hostnamectl set-hostname "$(sed -n '/127.0.0.1/p' /etc/hosts | cut -d' ' -f3)"

sudo apt-get install -y software-properties-common
sudo add-apt-repository -y ppa:vbernat/haproxy
sudo apt-get update
sudo apt-get install -y haproxy
CONFIG="
frontend http
  bind *:80
  mode http
  default_backend web-backend

backend web-backend
  balance roundrobin
  server 181596-web-01 100.26.168.39:80 check
  server 181596-web-02 54.157.140.196:80 check
"
echo "$CONFIG" | sudo tee -a /etc/haproxy/haproxy.cfg > /dev/null

sudo service haproxy restart
